# Generated by Django 5.1.5 on 2025-02-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_cinema_logo_movie_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="screening",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("doorsopen", "Doors Open"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="scheduled",
                max_length=10,
            ),
        ),
    ]
