# Generated by Django 5.1.5 on 2025-02-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_screening_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="screening",
            name="roomscreen",
            field=models.BooleanField(default=False),
        ),
    ]
