# Generated by Django 5.1.5 on 2025-02-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_screening_roomscreen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="screening",
            old_name="roomscreen",
            new_name="display",
        ),
    ]
