# Generated by Django 5.1.5 on 2025-02-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_rename_roomscreen_screening_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(
                default="movie_posters/default.jpg", upload_to="movie_posters/"
            ),
        ),
    ]
